import type { Metadata } from "next";
import { LINE_Seed_JP, Geist_Mono } from "next/font/google"
import "./globals.css";

const lineSeedJp = LINE_Seed_JP({
  preload: true,
  weight: ["100", "400", "700", "800"],
  subsets: ["latin"],
  variable: "--font-line-seed-jp",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${lineSeedJp.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
